### ISSUE TITLE
What is the user experience?

### ISSUE THREAD

**Issue by LucasCioffi** [opentok/screensharing-extensions#2]
This looks promising.  A few questions:

1. Do all users who wish to broadcast their screen need to install either the Chrome or Firefox extension? 
2. After they do so, do they need to refresh the page or restart the browser?
3. Is it possible for a user to stream both their screen and their webcam at the same time?

**Comment by aullman** [comment]
1. Yes.
2. Just refresh the page, no need to restart the browser.
3. Yes, you just need to create 2 Publishers.

**Comment by LucasCioffi** [comment]
Great.  Thank you.
