### ISSUE TITLE
Problems with unpacked chrome extension not recognized as installed

### ISSUE THREAD

**Issue by maca** [opentok/screensharing-extensions#4]
I am trying to follow the instructions for having screensharing implemented under chrome, I've cloned the repo and edited the chrome extension manifest to match my development domain for my web app. 
I've also installed the unpacked modified extension and copied the generated id.

The problem I am facing is that the response object passed to the call back when calling `OT.checkScreenSharingCapability` has some unexpected property values: `extensionRegistered` value is `true` and `extensionInstalled` value is `false` even though i've used the id for the installed unpacked extension. The other weird thing is that if I substitute the extension id when calling `OT.registerScreenSharingExtension` with an arbitrary string still sets `extensionRegistered` value to `true`, so I have no idea what extensionRegistered stands for since the id does not corresponds to an actual extension.

     OT.registerScreenSharingExtension('chrome', 'MI-MODIFIED-EXTENSION-ID');
     OT.checkScreenSharingCapability(function(response) { console.log(response) });
  
I have no experience developing chrome extensions, Do I have to pack and publish the extension for my development environment? can I just install the unpacked extension?

Sorry if is not the proper channel to pose my questions, I've also filled a support ticket to TokBox.

**Comment by thepatrick** [comment]
`extensionRegistered` simply means that you have called `OT.registerScreenSharingExtension` with an extension for the current browser (only applies to Chrome).

If you are not seeing `extensionInstalled` then one of the following is likely the cause:

1. The ID is incorrect. (Unfortunately we don't have a way of determining this!)
2. The `clientScripts.matches` in your extensions manifest.json does not match the page you are testing with. Check that the protocol matches and try using a wildcard (e.g. `"matches": ["https://localhost/*"]`)

If either of these helps please update your support ticket so support know.

**Comment by krokhale** [comment]
I had the same issue, also had a few tries and reloads before i got the extension installed as unpacked source and i am guessing all those tries messed it up initially. But after adding patrick's point 2 and a bunch of reloads and restarting chrome, it seems to work fine.

**Comment by krokhale** [comment]
Just adding to this from my last comment, the dev environment seems to work great for me. I packed and published it to the chrome store and i am facing a weird issue:

Detecting extension:

    $scope.addScreenQ = () ->        
        OT.checkScreenSharingCapability (response) ->
           if response.extensionInstalled == false
             $rootScope.$apply ->
               $rootScope.modalHeader = 'Gilders Screen sharing extension'
               $rootScope.modalContent = $sce.trustAsHtml('Please install the screen sharing extension.')
              $rootScope.modalButtonText = 'Add to Chrome'
              $('.modal').modal({backdrop:false})

            $rootScope.onModalButtonClick = (e) ->
              e.preventDefault()
              $('.modal').modal('hide')
              chrome.webstore.install(
                  'https://chrome.google.com/webstore/detail/oosunjnkgbfgmkcecjkoakoednbgljbkdnhhncp',         
                  onChromeSuccess, onChromeFail)

              onChromeSuccess = (event) ->
                // do something
                
              onChromeFail = (event) ->
                // do something


That gives me the chrome popup to install the extension and everything seems fine until that point. And i double check my extensions and yes it's installed. Now i refresh the page and look for:

     response.extensionInstalled
     chrome.app.isInstalled 

Both are always false, what am i missing??

Thanks!

**Comment by krokhale** [comment]
Also, yes i do register it

     OT.registerScreenSharingExtension('chrome', 'oosunjnkgbfgmkcecjkoakoednbgljbkdnhhncp')

before i query 

     response.extensionInstalled
     chrome.app.isInstalled

**Comment by krokhale** [comment]
The extensions seem to have a lot of inconsistencies and i am not sure it's ready for production. Though i got mine working, it just feels too much of a hack.

1) The response from OT.checkScreenSharingCapability, returns conflicting data. response.extensionInstalled should either return true or false, but it is not normalized and returns undefined in case of firefox and false in case of chrome.

2) OT.checkScreenSharingCapability does not seem to recognize a valid firefox extension at all. So instead of checking it before publishing, the check for firefox has to be performed on the error callback of OT.initPublisher.

**Comment by thepatrick** [comment]
@krokhale the docks for `OT.checkScreenSharingCapability` should set shed some light here https://tokbox.com/opentok/libraries/client/js/reference/OT.html#checkScreenSharingCapability

1) `extensionInstalled` is `true`, `false` (when `extensionRequired` is also set to `"chrome"`) or `undefined` (when `extensionRequired` is also set to `undefined`)

2) Basically Firefox does not require an extension (you can be added to the default whitelist either globally by Mozilla or manually locally), so `OT.checkScreenSharingCapability` does not check for this. At this time you will need to check for the installation of the Firefox extension yourself.

**Comment by thepatrick** [comment]
Also if `response.extensionInstalled` is false then for whatever reason Chrome is not injecting the extension on the page - this is most likely because the extension ID (given to `OT.registerScreenSharingExtension`) or the `matches` key (in `manifest.json`) does not match the URL you are calling `OT.checkScreenSharingCapability` on.
