### ISSUE TITLE
Where I will place my js code for share the screen

### ISSUE THREAD

**Issue by mssrandhir** [opentok/screensharing-extensions#5]
Am using this repo to build screen share extension for Firefox, As you mentioned 
this code will share the screen, please explain bit more where this file will be placed and how is it added to .xpi file the will be the final build for the extension.
To publish a screen:

```javascript
var publisher = OT.initPublisher('target-element-id', {
  name: 'Screen',
  audioSource: null,
  videoSource: 'screen',
  maxResolution: { width: 1280, height: 720 }, // max resolution to encode screen in
  width: 1280, // width of preview
  height: 720, // height of preview
}, function(error) {
  if(error) {
    // handle the error
  }
  // resize the publisher preview to match the encoded video
  pub.element.style.width = pub.videoWidth() + 'px';
  pub.element.style.height = pub.videoHeight() + 'px';
});

**Comment by thepatrick** [comment]
That code would most likely not be in the .xpi itself, it would be in a HTML page loaded over SSL.

I'd suggest you take a look at the [Screen sharing - Javascript][0] tutorial - it explains how to get started.

[0]: https://tokbox.com/opentok/tutorials/screen-sharing/js/
