### ISSUE TITLE
How to Show My Shared Screen on My Screen?

### ISSUE THREAD

**Issue by LucasCioffi** [opentok/screensharing-extensions#7]
With Google Hangout, a user can see the result of their own shared screen, so that they know it's working.  I'd like to do the same and have added this:

    <div id="camera-publisher"></div>

Is this the part that needs to be modified to show the user their own shared screen?  What would you add?

    session.on('streamCreated', function(event) {
      if (event.stream.videoType === 'screen') {
        // This is a screen-sharing stream published by another client 
        var subOptions = {
          width: event.stream.videoDimensions.width * .8,
          height: event.stream.videoDimensions.height * .8
        };
        session.subscribe(event.stream, 'screen-subscriber', subOptions);
      } else {
        // This is a stream published by another client using the camera and microphone
        session.subscribe(event.stream, 'camera-subscriber');
      }
    });

Thank you!

**Comment by aullman** [comment]
You don't need to do anything special to see your own screen. Your publisher will display your own screen. No need to subscribe to yourself.

**Comment by LucasCioffi** [comment]
That's great.  For some reason I can share my screen with others (so it is working) but it's not visible on my page.  My video is visible on my page.  

My code is below.  Is there something obvious that I'm doing wrong?

    <html>
    <body>
      <div style='text-align:right; position:relative; z-index:10; left:-10px;'><span style='cursor:pointer;' class='linklike' onClick="window.parent.closeScreensharing();"><img src='/close.png' alt='close the screensharing section'></span></div>
      <button onclick="javascript:screenshare();" disabled id="shareBtn" class="smaller_text btn">Share your screen</button>
      <div id="camera-subscriber"></div>
      <div id="screen-subscriber"></div>
      <script src="//static.opentok.com/v2/js/opentok.js"></script>
      <script type="text/javascript">
    
        // Go to https://dashboard.tokbox.com/ to get your OpenTok API Key and to generate
        // a test session ID and token:
        var apiKey    = "1234567";
        var sessionId = "<%= @session_id %>";
        var token     = "<%= @token %>";

        // Replace this with the ID for your Chrome screen-sharing extension, which you can
        // get at chrome://extensions/:
    
        var extensionId = 'hello@mysite.com';

        var session = OT.initSession(apiKey, sessionId);

        session.connect(token, function(error) {
          // publish a stream using the camera and microphone:
          var publisher = OT.initPublisher('camera-publisher');
          session.publish(publisher);
          document.getElementById('shareBtn').disabled = false;
        });

        session.on('streamCreated', function(event) {
          if (event.stream.videoType === 'screen') {
            // This is a screen-sharing stream published by another client 
            var subOptions = {
              width: event.stream.videoDimensions.width * .8,
              height: event.stream.videoDimensions.height * .8
            };
            session.subscribe(event.stream, 'screen-subscriber', subOptions);
          } else {
            // This is a stream published by another client using the camera and microphone
            session.subscribe(event.stream, 'camera-subscriber');
          }
        });

        // For Google Chrome only, register your extension by ID,
        // You can find it at chrome://extensions once the extension is installed
        OT.registerScreenSharingExtension('chrome', extensionId);

        function screenshare() {
          OT.checkScreenSharingCapability(function(response) {
            if (!response.supported || response.extensionRegistered === false) {
              alert('This browser does not support screen sharing.');
            } else if (response.extensionInstalled === false) {
              alert('Please install the screen sharing extension.');
            } else {
              // Screen sharing is available. Publish the screen.
              // Create an element, but do not display it in the HTML DOM:
              var screenContainerElement = document.createElement('div');
              var screenSharingPublisher = OT.initPublisher(
                screenContainerElement,
                { videoSource : 'screen' },
                function(error) {
                  if (error) {
                    alert('Something went wrong: ' + error.message);
                  } else {
                    session.publish(
                      screenSharingPublisher,
                      function(error) {
                        if (error) {
                          alert('Something went wrong: ' + error.message);
                        }
                      });
                  }
                });
              }
            });
        }
      </script>
    </body>
    </html>

**Comment by aullman** [comment]
Yes, you're never putting the screenContainerElement anywhere. You need something like `document.body.appendChild(screenContainerElement);`

**Comment by LucasCioffi** [comment]
Thank you @aullman.

**Comment by LucasCioffi** [comment]
@aullman If we do not append screenContainerElement do we still get charged for the stream?  By not appending, do we also save CPU and Internet bandwidth for the presenter?

**Comment by aullman** [comment]
No, you won't save anything. You're still encoding the video and sending it to the other participants regardless of whether you are displaying it to yourself. You will still be charged too :)
